modLoader="javafml"
loaderVersion="[37,)"
issueTrackerURL="https://github.com/ochotonida/potheads/issues"
license="MIT"

[[mods]]
modId = "potheads"
version = "1.17.1-1.0.0"
displayName = "PotHeads"
displayURL="https://www.curseforge.com/minecraft/mc-mods/potheads" # TODO
logoFile="logo.png" # TODO
description='''Adds potted plants as items'''

[[dependencies.potheads]]
    modId="forge"
    mandatory=true
    versionRange="[37.0.104,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.potheads]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"

[[dependencies.potheads]]
    modId="curios"
    mandatory=false
    versionRange="[1.17.1-5.0.1.0,)"
    ordering="AFTER"
    side="BOTH"