modLoader="javafml"
loaderVersion="[38,)"
issueTrackerURL="https://github.com/ochotonida/potheads/issues"
license="MIT"

[[mods]]
modId = "potheads"
version = "1.18-1.0.0"
displayName = "PotHeads"
displayURL="https://www.curseforge.com/minecraft/mc-mods/potheads"
logoFile="logo.png"
description='''Adds potted plants as items'''

[[dependencies.potheads]]
    modId="forge"
    mandatory=true
    versionRange="[38.0.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.potheads]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"

[[dependencies.potheads]]
    modId="curios"
    mandatory=false
    versionRange="[1.18-5.0.2.1,)"
    ordering="AFTER"
    side="BOTH"